/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sakila.ui;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import sakila.entity.Film;
import sakila.util.HibernateUtil;

/**
 *
 * @author jagd_
 */
public class ConsultaPelicula extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPelicula
     */
    public ConsultaPelicula() {
        initComponents();
        //añado los botones de radio al buttonGroup para su correcto funcionamiento
        buttonGroup_consulta.add(jRadioButton_titulo);
        buttonGroup_consulta.add(jRadioButton_descripcion);
        buttonGroup_consulta.add(jRadioButton_caracteristica);
        
        //hacemos que aparezca maximizado el JFrame
        setExtendedState(this.MAXIMIZED_BOTH);
        //posicionamos el frame en el centro de la pantalla
        setLocationRelativeTo(null);
        
        //cremos la cabecera de la tabla
        tableHeaders = new Vector<String>();
        tableHeaders.add("Película Id");
        tableHeaders.add("Título");
        tableHeaders.add("Descripción");
        tableHeaders.add("Año de lanzamiento");
        tableHeaders.add("Idioma Id");
        tableHeaders.add("Idioma original Id");
        tableHeaders.add("Duración del alquiler");
        tableHeaders.add("Tasa de arrendamiento");
        tableHeaders.add("Duración");
        tableHeaders.add("Coste de sustitución");
        tableHeaders.add("Clasificación");
        tableHeaders.add("Características especiales");
        tableHeaders.add("Actualizado");
        //añadimos la cabecera a la Jtable para que se visualice al abrirse el formulario
        tbListado.setModel(new DefaultTableModel(null, tableHeaders));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_consulta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListado = new javax.swing.JTable();
        jRadioButton_titulo = new javax.swing.JRadioButton();
        jRadioButton_descripcion = new javax.swing.JRadioButton();
        jRadioButton_caracteristica = new javax.swing.JRadioButton();
        jTextField_consulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso a Datos Tema 4. Consultas con Hibernate. ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta Película");

        btConsulta.setText("Consulta");
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        tbListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbListado);

        jRadioButton_titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jRadioButton_titulo.setText("Título");
        jRadioButton_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_tituloActionPerformed(evt);
            }
        });

        jRadioButton_descripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jRadioButton_descripcion.setText("Descripción");
        jRadioButton_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_descripcionActionPerformed(evt);
            }
        });

        jRadioButton_caracteristica.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jRadioButton_caracteristica.setText("Características especiales");

        jTextField_consulta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField_consulta.setText(" ");
        jTextField_consulta.setToolTipText("Introducir el valor a consultar");
        jTextField_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_consultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jRadioButton_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_descripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_caracteristica)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btConsulta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsulta)
                    .addComponent(jRadioButton_titulo)
                    .addComponent(jRadioButton_descripcion)
                    .addComponent(jRadioButton_caracteristica)
                    .addComponent(jTextField_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        //recogemos lo que se introduce en el campo de texto
        String cadenaConsulta = jTextField_consulta.getText();
        
        //vemos que rdioButton se ha seleccionado
        if(jRadioButton_titulo.isSelected()){
            
            if (!cadenaConsulta.trim().equals("")) {
                
                ejecutaHQLConsulta(CONSULTA_BASADA_EN_TITULO + cadenaConsulta + "%'");
                
            } else{
                
                JOptionPane.showMessageDialog(null, "Debe introducir un título", "Título", JOptionPane.INFORMATION_MESSAGE);
                
            }  
            
        }else if(jRadioButton_descripcion.isSelected()){
            
            if (!cadenaConsulta.trim().equals("")) {
                
                ejecutaHQLConsulta(CONSULTA_BASADA_EN_DESCRIPCION + cadenaConsulta + "%'");
                
            } else{
                
                JOptionPane.showMessageDialog(null, "Debe introducir la descripción", "Descripción", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
        }else if(jRadioButton_caracteristica.isSelected()){
            
            if (!cadenaConsulta.trim().equals("")) {
                
                ejecutaHQLConsulta(CONSULTA_BASADA_EN_CARACTERISTICAS + cadenaConsulta + "%'");
                
            } else{
                
                JOptionPane.showMessageDialog(null, "Debe introducir las características", "Características", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
        }
        
    }//GEN-LAST:event_btConsultaActionPerformed

    private void jRadioButton_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_descripcionActionPerformed
        // TODO add your handling code here:
        jTextField_consulta.setText("");
    }//GEN-LAST:event_jRadioButton_descripcionActionPerformed

    private void jTextField_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_consultaActionPerformed
        // TODO add your handling code here:
        jTextField_consulta.setText("");
    }//GEN-LAST:event_jTextField_consultaActionPerformed

    private void jRadioButton_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_tituloActionPerformed
        // TODO add your handling code here:
        jTextField_consulta.setText("");
    }//GEN-LAST:event_jRadioButton_tituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPelicula().setVisible(true);
            }
        });
    }

    //método que ejecuta la consulta recibida comoparámetro
    private void ejecutaHQLConsulta(String hql) {
        
        try {
            
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query consulta = session.createQuery(hql);
            List resultList = consulta.list();
            mostrarResultados(resultList);
            session.getTransaction().commit();
            
        } catch (HibernateException he) {
            he.printStackTrace();
        }
        
    }

    private void mostrarResultados(List resultList) {
        Vector<Object> oneRow;
        tableDatos = new Vector();
        
        for (Object o : resultList) {
            
            pelicula = (Film) o;
            
            oneRow = new Vector<Object>();
            oneRow.add(pelicula.getFilmId());
            oneRow.add(pelicula.getTitle());
            oneRow.add(pelicula.getDescription());
            oneRow.add(pelicula.getReleaseYear());
            oneRow.add(pelicula.getLanguageByLanguageId());
            oneRow.add(pelicula.getLanguageByOriginalLanguageId());
            oneRow.add(pelicula.getRentalDuration());
            oneRow.add(pelicula.getRentalRate());
            oneRow.add(pelicula.getLength());
            oneRow.add(pelicula.getReplacementCost());
            oneRow.add(pelicula.getRating());
            oneRow.add(pelicula.getSpecialFeatures());
            oneRow.add(pelicula.getLastUpdate());
            
            tableDatos.add(oneRow);
        }
        
        tbListado.setModel(new DefaultTableModel(tableDatos, tableHeaders));
    }
    
    private static String CONSULTA_BASADA_EN_TITULO = "from Film a where a.title like '";
    private static String CONSULTA_BASADA_EN_DESCRIPCION = "from Film a where a.description like '";
    private static String CONSULTA_BASADA_EN_CARACTERISTICAS = "from Film a where a.specialFeatures like '";
    
    private Vector<String> tableHeaders;
    private Vector tableDatos;
    private Film pelicula;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsulta;
    private javax.swing.ButtonGroup buttonGroup_consulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton_caracteristica;
    private javax.swing.JRadioButton jRadioButton_descripcion;
    private javax.swing.JRadioButton jRadioButton_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_consulta;
    private javax.swing.JTable tbListado;
    // End of variables declaration//GEN-END:variables
}

