/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import static Aplicacion.AplicacionTarea3.miIcono;
import java.sql.SQLException;
import java.util.Locale;
import javax.swing.*;
import javax.swing.event.*;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author AnaIglesias
 */
public class MarcoInsertarOrdenes extends javax.swing.JDialog {

    private JComboBox boxDatos;
    private String codigo;
    private String[] datos = new String[3];
    /**
     * Creates new form MarcoInsertarOrdenes
     */
    public MarcoInsertarOrdenes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(miIcono);
        //Establecemos el español para los mensajes de error
        Locale.setDefault(new Locale("es","ES"));
        jButton_aceptar.setEnabled(false);
        setLocationRelativeTo(null);
        
        //creamoa la conexión para almacenar en el comboBox todos los empleados 
        SQLClass query = new SQLClass();
        query.conectar();
        query.setRS("Select * from Empleados");
       
        try {
            //recorremos el Resultset rellenando con los datos el ComboBox
            while(query.getRS().next()){
                jComboBox_empleados.addItem(query.getRS().getString(1)+" => "+query.getRS().getString(2));
               
            }
               
            //cerramos la conexión para liberar recursos
            query.cerrarConexion();
               
        } catch (SQLException ex) {
                ex.printStackTrace();
        }
            
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(jTextField_codigo, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextField_nombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
        
        validationPanel.addChangeListener(new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanel.getProblem()== null){
                    jButton_aceptar.setEnabled(true);
                }else{
                    jButton_aceptar.setEnabled(false);
                }
            }
            
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_insertaOrdenes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jComboBox_empleados = new javax.swing.JComboBox<>();
        jButton_aceptar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(MarcoInsertarOrdenes.class, "MarcoInsertarOrdenes.title")); // NOI18N

        jPanel_insertaOrdenes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(MarcoInsertarOrdenes.class, "MarcoInsertarOrdenes.jPanel_insertaOrdenes.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(MarcoInsertarOrdenes.class, "MarcoInsertarOrdenes.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(MarcoInsertarOrdenes.class, "MarcoInsertarOrdenes.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(MarcoInsertarOrdenes.class, "MarcoInsertarOrdenes.jLabel3.text")); // NOI18N

        jTextField_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_codigo.setName("Código"); // NOI18N

        jTextField_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_nombre.setName("Nombre"); // NOI18N

        jComboBox_empleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel_insertaOrdenesLayout = new javax.swing.GroupLayout(jPanel_insertaOrdenes);
        jPanel_insertaOrdenes.setLayout(jPanel_insertaOrdenesLayout);
        jPanel_insertaOrdenesLayout.setHorizontalGroup(
            jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_insertaOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_insertaOrdenesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_empleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_insertaOrdenesLayout.createSequentialGroup()
                        .addGroup(jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_insertaOrdenesLayout.createSequentialGroup()
                                .addGroup(jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addComponent(jTextField_nombre))))
                .addContainerGap())
        );
        jPanel_insertaOrdenesLayout.setVerticalGroup(
            jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_insertaOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel_insertaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jButton_aceptar.setText(org.openide.util.NbBundle.getMessage(MarcoInsertarOrdenes.class, "MarcoInsertarOrdenes.jButton_aceptar.text")); // NOI18N
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });

        jButton_limpiar.setText(org.openide.util.NbBundle.getMessage(MarcoInsertarOrdenes.class, "MarcoInsertarOrdenes.jButton_limpiar.text")); // NOI18N
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_insertaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_insertaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        SQLClass query = new SQLClass();
        query.conectar();
        codigo ="";
        
        //extraemos el código correcto del jComboBox
        String buscar = jComboBox_empleados.getSelectedItem().toString().substring(0, 9);
            //comprobamos los caracteres objenidos del ComboBox para asegurar el código correcto
            for(int i=0;i<buscar.length();i++){
                if (Character.isLetter(buscar.charAt(i)) || Character.isDigit(buscar.charAt(i))){
                    codigo += buscar.charAt(i);
                }
            }
        //guardamos los datos en la tabla para pasrlos a la consulta    
        datos[0] = jTextField_codigo.getText();
        datos[1] = jTextField_nombre.getText();    
        datos[2] = codigo;    
        
        query.insertar("Ordenes", datos);
        
        query.cerrarConexion();
        jTextField_codigo.setText("");
        jTextField_nombre.setText("");
        jComboBox_empleados.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        jTextField_codigo.setText("");
        jTextField_nombre.setText("");
        jComboBox_empleados.setSelectedIndex(0);
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JComboBox<String> jComboBox_empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_insertaOrdenes;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_nombre;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
}
