/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import static Aplicacion.AplicacionTarea3.miIcono;
import java.sql.SQLException;
import java.util.Locale;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.openide.util.Exceptions;

/**
 *
 * @author AnaIglesias
 */
public class MarcoActualizarEmpleado extends javax.swing.JDialog {

    private String[] datos = new String[3];
    String buscar, codigo="";
    SQLClass query;
    /**
     * Creates new form MarcoActualizarEmpleado
     */
    public MarcoActualizarEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(miIcono);
        //Establecemos el español para los mensajes de error
        Locale.setDefault(new Locale("es","ES"));
        jButton_aceptar.setEnabled(false);
        setLocationRelativeTo(null);
        
        
        //creamoa la conexión para almacenar en el comboBox todos los empleados 
        query = new SQLClass();
        query.conectar();
        query.setRS("Select * from Empleados");
       
        try {
            //recorremos el Resultset rellenando con los datos el ComboBox
            while(query.getRS().next()){
                jComboBox_empleados.addItem(query.getRS().getString(1)+" => "+query.getRS().getString(2)); 
            }
            
            //cerramos la conexión para liberar recursos
            query.cerrarConexion();   
        } catch (SQLException ex) {
                ex.printStackTrace();
        }
            
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(jTextField_codigo, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextField_nombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextField_telefono, StringValidators.REQUIRE_NON_EMPTY_STRING);
        validationPanel.addChangeListener(new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanel.getProblem()== null){
                    jButton_aceptar.setEnabled(true);
                }else{
                    jButton_aceptar.setEnabled(false);
                }
            }
            
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_insertaEmpleados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jButton_aceptar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_empleados = new javax.swing.JComboBox<>();
        jButton_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.title")); // NOI18N

        jPanel_insertaEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.jPanel_insertaEmpleados.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.jLabel3.text")); // NOI18N

        jTextField_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_codigo.setName("Código"); // NOI18N

        jTextField_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_nombre.setName("Nombre"); // NOI18N

        jTextField_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_telefono.setName("Teléfono"); // NOI18N

        javax.swing.GroupLayout jPanel_insertaEmpleadosLayout = new javax.swing.GroupLayout(jPanel_insertaEmpleados);
        jPanel_insertaEmpleados.setLayout(jPanel_insertaEmpleadosLayout);
        jPanel_insertaEmpleadosLayout.setHorizontalGroup(
            jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_insertaEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_insertaEmpleadosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_insertaEmpleadosLayout.createSequentialGroup()
                        .addGroup(jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre)
                            .addGroup(jPanel_insertaEmpleadosLayout.createSequentialGroup()
                                .addGroup(jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 48, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel_insertaEmpleadosLayout.setVerticalGroup(
            jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_insertaEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel_insertaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jButton_aceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_aceptar.setText(org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.jButton_aceptar.text")); // NOI18N
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });

        jButton_limpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_limpiar.setText(org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.jButton_limpiar.text")); // NOI18N
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.jLabel4.text")); // NOI18N

        jComboBox_empleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_empleadosActionPerformed(evt);
            }
        });

        jButton_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_buscar.setText(org.openide.util.NbBundle.getMessage(MarcoActualizarEmpleado.class, "MarcoActualizarEmpleado.jButton_buscar.text")); // NOI18N
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel_insertaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_buscar)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel_insertaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        /*si lo introducido en el campo excede del tamaño declarado se trunca
          para evitar error
        */
        if (jTextField_telefono.getText().length()>8){
           jTextField_telefono.setText(jTextField_telefono.getText().substring(0, 9));
        }
         //cargamos el array con los datos para realizar la actualización
        datos[0] = jTextField_codigo.getText();
        datos[1] = jTextField_nombre.getText();
        datos[2] = jTextField_telefono.getText();
        //Objeto para la conexión a la base de datos
        SQLClass query = new SQLClass();
        query.conectar();
        //actualizamos los datos en la tabla empleados
        query.actualiza("EMPLEADOS", datos);
        query.cerrarConexion();
        dispose();
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        //jTextField_codigo.setText("");
        jTextField_nombre.setText("");
        jTextField_telefono.setText("");
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jComboBox_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_empleadosActionPerformed
        
    }//GEN-LAST:event_jComboBox_empleadosActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        codigo = "";
        try {
            query.conectar();
            //obtengo el empleado seleccionado
            buscar = jComboBox_empleados.getSelectedItem().toString().substring(0, 9);
            //comprobamos los caracteres obtenidos del ComboBox para asegurar el código correcto
            for(int i=0;i<buscar.length();i++){
                if (Character.isLetter(buscar.charAt(i)) || Character.isDigit(buscar.charAt(i))){
                    codigo += buscar.charAt(i);
                }
            }
            
            String consulta = "Select * from Empleados Where Codigo_Empleado = '"+codigo+"'";
            
            query.setRS(consulta);
            
            if (query.getRS().next()){
            
                //visualizamos los datos del empleado seleccionado
                jTextField_codigo.setText(query.getRS().getString(1));
                jTextField_codigo.setEditable(false);
                jTextField_nombre.setText(query.getRS().getString(2));
                jTextField_telefono.setText(query.getRS().getString(3));
                jButton_aceptar.setEnabled(true);
                
            }
            
            query.cerrarConexion();
            
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptar;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JComboBox<String> jComboBox_empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_insertaEmpleados;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_telefono;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
}
