/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import static Aplicacion.AplicacionTarea3.miIcono;
import java.sql.*;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.*;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author AnaIglesias
 */
public class SentenciaPreparadaEmpleado extends javax.swing.JDialog {

    String buscar, codigo;
    SQLClass query = new SQLClass();
    private PreparedStatement enviaConsulta;
    private String consultaEmpleado;
    /**
     * Creates new form SentenciaPreparadaEmpleado
     */
    public SentenciaPreparadaEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(miIcono);
        //Establecemos el español para los mensajes de error
        Locale.setDefault(new Locale("es","ES"));
        jButton_aceptar.setEnabled(false);
        setLocationRelativeTo(null);
        
        
        //creamoa la conexión para almacenar en el comboBox todos los empleados 
        query = new SQLClass();
        query.conectar();
        query.setRS("Select * from Empleados");
       
        try {
            //recorremos el Resultset rellenando con los datos el ComboBox
            while(query.getRS().next()){
                jComboBox_Empleados.addItem(query.getRS().getString(1)+" => "+query.getRS().getString(2)); 
            }
            
            //cerramos la conexión para liberar recursos
            query.cerrarConexion();   
        } catch (SQLException ex) {
                ex.printStackTrace();
        }
            
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(jTextField_codigo, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextField_nombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextField_telefono, StringValidators.REQUIRE_NON_EMPTY_STRING);
        validationPanel.addChangeListener(new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanel.getProblem()== null){
                    jButton_aceptar.setEnabled(true);
                }else{
                    jButton_aceptar.setEnabled(false);
                }
            }
            
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_Empleados = new javax.swing.JComboBox<>();
        jButton_buscar = new javax.swing.JButton();
        jPanel_actualizaEmpleados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jButton_aceptar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.title")); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.jLabel1.text")); // NOI18N

        jButton_buscar.setText(org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.jButton_buscar.text")); // NOI18N
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jPanel_actualizaEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.jPanel_actualizaEmpleados.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.jLabel3.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.jLabel4.text")); // NOI18N

        jTextField_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_codigo.setName("Código"); // NOI18N

        jTextField_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_nombre.setName("Nombre"); // NOI18N

        jTextField_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_telefono.setName("Teléfono"); // NOI18N

        javax.swing.GroupLayout jPanel_actualizaEmpleadosLayout = new javax.swing.GroupLayout(jPanel_actualizaEmpleados);
        jPanel_actualizaEmpleados.setLayout(jPanel_actualizaEmpleadosLayout);
        jPanel_actualizaEmpleadosLayout.setHorizontalGroup(
            jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_actualizaEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_actualizaEmpleadosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_actualizaEmpleadosLayout.createSequentialGroup()
                        .addGroup(jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre)
                            .addGroup(jPanel_actualizaEmpleadosLayout.createSequentialGroup()
                                .addGroup(jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel_actualizaEmpleadosLayout.setVerticalGroup(
            jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_actualizaEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel_actualizaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jButton_aceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_aceptar.setText(org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.jButton_aceptar.text")); // NOI18N
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });

        jButton_limpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_limpiar.setText(org.openide.util.NbBundle.getMessage(SentenciaPreparadaEmpleado.class, "SentenciaPreparadaEmpleado.jButton_limpiar.text")); // NOI18N
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_buscar)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_actualizaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_actualizaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        try {

            if (jTextField_telefono.getText().length()>8){
                jTextField_telefono.setText(jTextField_telefono.getText().substring(0, 9));
            }
            
            query.conectar();
            //consulta preparada de actualización
            String stn_actualiza = "UPDATE EMPLEADOS SET "
                    + "Nombre_Empleado = ?,"
                    + "Telefono = ?"
                    + " WHERE codigo_Empleado = ?";
            enviaConsulta = query.getCN().prepareStatement(stn_actualiza);
            enviaConsulta.setString(1, jTextField_nombre.getText());
            enviaConsulta.setString(2, jTextField_telefono.getText());
            enviaConsulta.setString(3, jTextField_codigo.getText());
            enviaConsulta.executeUpdate();
            enviaConsulta.close();
            JOptionPane.showMessageDialog(null, "Registro modificado correctamente", null, JOptionPane.INFORMATION_MESSAGE);
            query.cerrarConexion();
            dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        jTextField_codigo.setText("");
        jTextField_nombre.setText("");
        jTextField_telefono.setText("");
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        try {
            query.conectar();
            codigo="";
            //obtengo el empleado seleccionado
            buscar = jComboBox_Empleados.getSelectedItem().toString().substring(0, 9);
            //comprobamos los caracteres objenidos del ComboBox para asegurar el código correcto
            for(int i=0;i<buscar.length();i++){
                /*La longitud del codigo del empleado es de 9 caracteres pero si se introducen
                  codigos de inferior longitud al presentarlos en el jComboBox junto al nombre
                  extraigo el código correcto para evitar errores en la basse de datos
                */
                if (Character.isLetter(buscar.charAt(i)) || Character.isDigit(buscar.charAt(i))){
                    codigo += buscar.charAt(i);
                }
            }
            //sentencis preparada para buscar el empleado
            consultaEmpleado = "Select * from Empleados WHERE codigo_Empleado = ?";
            enviaConsulta = query.getCN().prepareStatement(consultaEmpleado);
            //indicamos el parámetro para la consulta
            enviaConsulta.setString(1, codigo);
            //ejecutamos la consulta
            ResultSet rs = enviaConsulta.executeQuery();
            if (rs.next()){
            
                //visualizamos los datos del empleado seleccionado
                jTextField_codigo.setText(rs.getString(1));
                jTextField_codigo.setEditable(false);
                jTextField_nombre.setText(rs.getString(2));
                jTextField_telefono.setText(rs.getString(3));
                jButton_aceptar.setEnabled(true);
            }
            
            query.cerrarConexion();
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptar;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JComboBox<String> jComboBox_Empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_actualizaEmpleados;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_telefono;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
}
